# Create Data
import json

faq_data = [
    {"question": "What is the company's leave policy?",
        "answer": "Employees are entitled to 20 paid leaves per year."},
    {"question": "How do I apply for leave?",
        "answer": "You can apply for leave via the portal under the 'Leave' tab."},
    {"question": "Can I carry forward unused leaves?",
        "answer": "Yes, up to 10 days can be carried forward to the next year."},
    {"question": "What are the official working hours?",
        "answer": "Working hours are from 9 AM to 6 PM, Monday to Friday."},
    {"question": "Is there a dress code at the office?",
        "answer": "Smart casuals are expected from Monday to Thursday; Friday is casual wear."},
    {"question": "What is the notice period for resignation?",
        "answer": "The standard notice period is 2 months."},
    {"question": "Does the company provide health insurance?",
        "answer": "Yes, we offer health insurance for employees and their dependents."},
    {"question": "How do I update my personal details?",
        "answer": "You can update your personal information in your profile under 'My Info'."},
    {"question": "When is the salary credited?",
        "answer": "Salary is credited by the 5th of every month."},
    {"question": "Are there any performance bonuses?",
        "answer": "Yes, performance bonuses are given annually based on individual and company performance."},
    {"question": "What holidays are observed by the company?",
        "answer": "The company observes all national holidays and 10 additional company holidays."},
    {"question": "How can I access my payslip?",
        "answer": "Payslips are available monthly on the HRMS portal under the 'Payroll' section."},
    {"question": "What is the policy for working from home?",
        "answer": "Employees may work from home up to 2 days per week with manager approval."},
    {"question": "Is there a maternity/paternity leave policy?",
        "answer": "Yes, maternity leave is 26 weeks and paternity leave is 15 days."},
    {"question": "What training programs does the company offer?",
        "answer": "The company offers training in technical skills, soft skills, and leadership development."},
    {"question": "How do I apply for internal job openings?",
        "answer": "Internal job openings are posted on the HR portal and can be applied for through your employee account."},
    {"question": "Are there opportunities for promotion?",
        "answer": "Yes, promotions are based on performance reviews and business needs."},
    {"question": "What is the company’s policy on workplace harassment?",
        "answer": "The company has a zero-tolerance policy on harassment, and complaints can be filed confidentially with HR."},
    {"question": "How can I request a salary advance?",
        "answer": "Salary advances can be requested via the HRMS portal and require manager approval."},
    {"question": "What benefits does the company provide?",
        "answer": "Benefits include health insurance, provident fund, gratuity, and wellness programs."},
    {"question": "Is overtime compensated?",
        "answer": "Yes, overtime is compensated either by pay or time off, depending on employment terms."},
    {"question": "How do I apply for a transfer to another department?",
        "answer": "Submit a transfer request form through HRMS; approvals depend on availability and manager consent."},
    {"question": "Are there employee wellness programs?",
        "answer": "Yes, the company provides wellness programs including fitness classes and counseling."},
    {"question": "How do I report a workplace injury?",
        "answer": "Report immediately to your manager and HR; an incident report will be filed."},
    {"question": "What is the probation period?",
        "answer": "The standard probation period is 6 months."},
    {"question": "Can I take unpaid leave?",
        "answer": "Unpaid leave may be granted under special circumstances with prior approval."},
    {"question": "What is the policy on office attendance and punctuality?",
        "answer": "Employees are expected to adhere to working hours; repeated tardiness may result in disciplinary action."},
    {"question": "How do I apply for educational reimbursement?",
        "answer": "You can apply for educational reimbursement through HR with prior approval and submission of course details."},
    {"question": "Is parking available for employees?",
        "answer": "Yes, parking is provided on a first-come, first-served basis."},
    {"question": "What is the procedure for employee grievance?",
        "answer": "Grievances can be submitted confidentially to HR via email or the grievance portal."},
    {"question": "Do employees get paid time off for voting?",
        "answer": "Yes, employees are allowed paid time off to vote during elections."},
    {"question": "Are employees eligible for retirement benefits?",
        "answer": "Yes, retirement benefits include provident fund and gratuity as per company policy."},
    {"question": "What is the company’s policy on social media use?",
        "answer": "Employees should use social media responsibly and avoid sharing confidential information."},
    {"question": "How do I apply for a leave extension?",
        "answer": "Submit a leave extension request through the HRMS portal before your current leave expires."},
    {"question": "Can I work part-time?",
        "answer": "Part-time work is considered on a case-by-case basis and requires management approval."},
    {"question": "Are there any employee referral programs?",
        "answer": "Yes, employee referrals are encouraged with bonuses for successful hires."},
    {"question": "How do I update my emergency contact information?",
        "answer": "Emergency contacts can be updated in your HRMS profile under 'Personal Details'."},
    {"question": "What is the company's policy on remote work equipment?",
        "answer": "The company provides laptops and necessary accessories for approved remote work."},
    {"question": "Is there a dress code for virtual meetings?",
        "answer": "Professional attire is recommended for virtual meetings."},
    {"question": "What holidays do part-time employees receive?",
        "answer": "Part-time employees receive prorated holidays based on hours worked."},
    {"question": "How do I apply for sabbatical leave?",
        "answer": "Sabbatical leave requires at least 3 years of service and management approval."},
    {"question": "What is the policy on travel expenses?",
        "answer": "Approved travel expenses are reimbursed as per company guidelines upon submission of receipts."},
    {"question": "Does the company provide childcare support?",
        "answer": "Yes, we offer childcare subsidies and partnerships with local daycare centers."},
    {"question": "Are employees eligible for stock options?",
        "answer": "Eligible employees may participate in the company’s stock option plan."},
    {"question": "What is the process for exit interviews?",
        "answer": "Exit interviews are scheduled by HR before your last working day."},
    {"question": "How do I report a technical issue?",
        "answer": "Submit a ticket through the IT helpdesk portal."},
    {"question": "Are bonuses taxable?",
        "answer": "Yes, bonuses are subject to applicable taxes as per government regulations."},
    {"question": "What is the company's policy on confidentiality?",
        "answer": "Employees must maintain confidentiality of all proprietary information at all times."},
    {"question": "How do I request flexible working hours?",
        "answer": "Submit a request to your manager outlining the reason for flexible hours."},
    {"question": "Is there a policy for employee gifts?",
        "answer": "Gifts to employees should comply with company ethics and value limits."},
    {"question": "Are employees allowed to attend conferences?",
        "answer": "Yes, attendance at relevant conferences can be approved as part of professional development."},
    {"question": "What is the company's policy on smoking?",
        "answer": "Smoking is prohibited within company premises except in designated areas."},
    {"question": "How do I apply for medical leave?",
        "answer": "Medical leave requests must be supported with valid medical certificates."},
    {"question": "Are employees entitled to overtime pay on weekends?",
        "answer": "Yes, weekend overtime is compensated as per labor laws and company policy."},
    {"question": "What is the policy on employee awards?",
        "answer": "The company recognizes outstanding contributions through quarterly and annual awards."},
    {"question": "How do I update my bank account details for salary?",
        "answer": "Update your bank details through the payroll section in the HRMS portal."},
    {"question": "Is there a policy for internet usage at work?",
        "answer": "Internet usage should be work-related and comply with company guidelines."},
    {"question": "Can I volunteer for CSR activities?",
        "answer": "Yes, the company encourages employees to participate in CSR and community initiatives."},
    {"question": "What is the company’s approach to diversity and inclusion?",
        "answer": "We are committed to creating a diverse and inclusive workplace for all employees."},
    {"question": "How do I appeal a disciplinary action?",
        "answer": "You can appeal by submitting a written request to HR within 7 days of the action."},
    {"question": "Are there any company-sponsored events?",
        "answer": "Yes, we host annual retreats, team-building events, and holiday parties."},
    {"question": "What is the process for submitting expense reports?",
        "answer": "Expense reports should be submitted within 30 days of incurring the expense via the finance portal."},
    {"question": "How do I apply for long-term disability benefits?",
        "answer": "Contact HR for the application process and required documentation."},
    {"question": "What is the policy on workplace safety?",
        "answer": "Safety protocols must be followed at all times; training is provided regularly."},
    {"question": "Can I take leave for jury duty?",
        "answer": "Yes, leave for jury duty is provided as per local laws."},
    {"question": "Are there any mental health support programs?",
        "answer": "The company offers confidential counseling and mental health resources."},
    {"question": "How do I get a copy of my employment contract?",
        "answer": "You can request a copy from HR or download it from the HRMS portal."},
    {"question": "What is the company’s policy on data privacy?",
        "answer": "Employee data is handled in compliance with applicable privacy laws and company policy."},
    {"question": "How do I report unethical behavior?",
        "answer": "Report anonymously through the ethics hotline or directly to HR."},
    {"question": "Are there opportunities for international assignments?",
        "answer": "International assignments are available based on business needs and employee eligibility."},
    {"question": "How is employee performance evaluated?",
        "answer": "Performance is reviewed bi-annually through goal setting and manager feedback."},
    {"question": "What are the guidelines for professional conduct?",
        "answer": "Employees are expected to behave respectfully and ethically at all times."},
    {"question": "What is the company's policy on mobile phone usage?",
        "answer": "Mobile phone use should not interfere with work and must follow company rules."},
    {"question": "Are there any subsidies for commuting?",
        "answer": "Yes, eligible employees receive commuting subsidies based on distance."},
    {"question": "How do I enroll in the company's retirement plan?",
        "answer": "Enrollment information is available through HR and during onboarding."},
    {"question": "Can I request time off for religious holidays?",
        "answer": "Yes, employees can request leave for religious observances with prior approval."},
    {"question": "What is the policy for employee breaks?",
        "answer": "Employees are entitled to a 1-hour lunch break and two 15-minute breaks daily."},
    {"question": "Are part-time employees eligible for benefits?",
        "answer": "Part-time employees may receive prorated benefits based on hours worked."},
    {"question": "How do I submit feedback about the workplace?",
        "answer": "Feedback can be submitted anonymously via the employee feedback portal."},
    {"question": "What is the policy on remote work during emergencies?",
        "answer": "Remote work is allowed during declared emergencies with manager approval."},
    {"question": "How can I update my tax withholding details?",
        "answer": "Tax details can be updated via the payroll section in the HRMS portal."},
    {"question": "Does the company support continuing education?",
        "answer": "Yes, we offer tuition reimbursement and support for approved courses."},
    {"question": "What is the company's stance on drug and alcohol use?",
        "answer": "The company maintains a drug-free workplace policy; violations may lead to disciplinary action."},
    {"question": "How do I apply for a leave of absence?",
        "answer": "Submit a leave of absence request form with appropriate documentation to HR."},
    {"question": "Are there mentoring programs available?",
        "answer": "Yes, employees can participate in mentoring programs to support career growth."},
    {"question": "What is the policy on internet security?",
        "answer": "Employees must follow IT security guidelines to protect company data."},
    {"question": "How are conflicts between employees resolved?",
        "answer": "Conflicts should be reported to HR for mediation and resolution."},
    {"question": "Can I bring a guest to company events?",
        "answer": "Guest policies vary; check event invitations for specific details."},
    {"question": "What is the procedure for requesting equipment?",
        "answer": "Submit equipment requests through the IT service portal with manager approval."},
    {"question": "Are there any restrictions on outside employment?",
        "answer": "Employees must disclose any outside employment and ensure no conflicts of interest."},
    {"question": "How do I request a reference letter?",
        "answer": "Request a reference from your manager or HR with advance notice."},
    {"question": "Is there a policy for social gatherings after work?",
        "answer": "Social gatherings are allowed but must comply with company conduct policies."},
    {"question": "What are the guidelines for using company vehicles?",
        "answer": "Company vehicle use requires authorization and adherence to safety policies."},
    {"question": "How can I participate in the company’s sustainability initiatives?",
        "answer": "Employees can join sustainability committees or volunteer for green projects."},
    {"question": "What is the process for employee onboarding?",
        "answer": "Onboarding includes orientation, paperwork, and training scheduled by HR."},
    {"question": "Hello", "answer": "Hello! How can I assist you today?"},
    {"question": "Hi", "answer": "Hi there! What can I help you with?"},
    {"question": "Good morning",
        "answer": "Good morning! Hope you have a great day ahead."},
    {"question": "Good afternoon",
        "answer": "Good afternoon! How can I assist you today?"},
    {"question": "Good evening",
        "answer": "Good evening! Hope you had a great day. How can I help?"},
    {"question": "Thank you",
        "answer": "You're welcome! If you have more questions, feel free to ask."},
    {"question": "Thanks", "answer": "Glad to help! Let me know if you need anything else."},
    {"question": "Bye", "answer": "Goodbye! Have a great day ahead."},
    {"question": "Have a great day", "answer": "Thank you! You too!"},
]

with open(r"D:\07-SANKET\Task\data.json", "w", encoding="utf-8") as f:
    json.dump(faq_data, f, indent=2)

print(" Create data.json with 100 real-life HR FAQs ")
